# Generated by Django 4.1.6 on 2023-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
