# Generated by Django 4.1.6 on 2023-02-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='unique_id',
            new_name='user_id',
        ),
    ]
