# Generated by Django 4.1.6 on 2023-02-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_unique_id_users_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
