# Generated by Django 4.1.6 on 2023-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soloevent',
            name='event_name',
            field=models.TextField(),
        ),
    ]
