# Generated by Django 4.1.6 on 2023-02-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0002_soloevent_event_id_alter_soloevent_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.TextField()),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.TextField()),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
