# Generated by Django 4.1.6 on 2023-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0003_teamevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.TextField()),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
