# Generated by Django 4.1.6 on 2023-02-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0004_teamdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamDetails',
            new_name='TeamDetail',
        ),
    ]
