# Generated by Django 4.1.6 on 2023-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0006_alter_teamdetail_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamevent',
            name='event_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamevent',
            name='team_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
