# Generated by Django 4.1.6 on 2023-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0007_alter_teamevent_event_name_alter_teamevent_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetail',
            name='team_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
