# Generated by Django 4.1.6 on 2023-02-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0008_alter_teamdetail_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
