# Generated by Django 4.1.6 on 2023-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0009_eventdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
