# Generated by Django 4.1.7 on 2023-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0010_eventdetail_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloContestRegistrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contest_slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventDetail',
        ),
    ]
