# Generated by Django 4.1.7 on 2023-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0011_solocontestregistrations_delete_eventdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamContestRegistrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contest_slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
