# Generated by Django 4.1.7 on 2023-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_events', '0012_teamcontestregistrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.TextField(blank=True, null=True)),
                ('leader_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamUserRegistrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamDetail',
        ),
    ]
