import React from 'react'
import Navbar from "../components/Navbar/Navbar";
// import Footer from "../components/Footer/Footer";
// import Slider from "../components/Slider/Slider";
import ScrollToTop from "../components/ScrollToTop/ScrollToTop";

export default function DefaultLayout({ children }) {
  return (
    <>
      {/* <Head>
        <title>Moksha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <ScrollToTop />
      <Navbar />
      {/* <Slider /> */}
      <div className="mt-20">{children}</div>
      {/* <Footer /> */}
    </>
  )
}
